version: '3.9'

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: custom-airflow:2.9.2-python3.9
  env_file:
    - airflow.env
  volumes:
    - ./config:/config
    - ./dags:/dags
    - ./data:/data
    - ./etls:/etls
    - ./logs:/logs
    - ./data_pipelines:/data_pipelines
    - ./plugins:/plugins
    - ./tests:/tests
    - ./utils:/utils
    - ./airflow.cfg:/home/user/airflow/airflow.cfg
    - ./requirements.txt:/requirements.txt
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_reddit
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "pip install -r requirements.txt && airflow db init && airflow db upgrade && airflow users create --username admin --firstname admin --lastname admin --role Admin --email airflow@airflow.com --password admin"
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    restart: always
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    restart: always
    user: root
    command: scheduler

  airflow-worker:
    <<: *airflow-common
    command: celery worker

volumes:
  postgres_data: